listeners:
- query_port: 25565
  motd: '&1Another Bungee server'
  tab_list: GLOBAL_PING
  query_enabled: false
  proxy_protocol: false
  forced_hosts:
    pvp.md-5.net: pvp
  ping_passthrough: false
  priorities:
  - lobby
  - Wizard
  bind_local_address: true
  host: 25.103.221.93:25565
  max_players: 1
  tab_size: 60
  force_default_server: true
remote_ping_cache: -1
network_compression_threshold: 256
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  - skinsrestorer.playercmds
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
log_pings: true
connection_throttle_limit: 3
server_connect_timeout: 5000
timeout: 30000
stats: 0a154c7d-d2a1-43bc-94b7-f2a994cfb616
player_limit: -1
ip_forward: true
groups:
  md_5:
  - admin
remote_ping_timeout: 5000
connection_throttle: 4000
log_commands: false
prevent_proxy_connections: false
online_mode: false
forge_support: false
disabled_commands:
- disabledcommandhere
servers:
  lobby:
    address: 25.103.221.93:25566
    restricted: false
    motd: '&cNOTHING'
  Wizard:
    motd: '&cCAM VAO :))'
    address: 25.103.221.93:25567
    restricted: false
